# -*- coding: utf-8 -*-
"""PROJECT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gn4RuAVC2YhBDqXaUMDrFZTW8fWvxioO

ASSIGNMENT
"""

def REGISTER() :
  db=open("databa.txt",'r')
  import re
  pattern="^[a-z]+[\._]?[a-z 0-9]+[@][a-z 0-9]+[\.][a-z]{2,3}$"
  d=[]
  f=[]
  for i in db :
    a,b=i.split(" ")
    b=b.strip()
    d.append(a)
    f.append(b)
  data = dict(zip(d, f))
  user_id=input("ENTER THE EMAIL ID:")
  if re.search(pattern, user_id):
    if user_id in d:
      print("email id already exist")
    else:
      pattern="((?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[@%$#]))"
      pass_id=input("ENTER THE PASSWORD:")
      if 5<len(pass_id)<16 :
        if re.search(pattern, pass_id):
          db=open("databa.txt","a")
          db.write(user_id+" "+pass_id+"\n")
          print("Registered")
        else:
          print("invalid password")
      else:
         print("password is too short or too long")
  else:
    print("invalid email_id")
def LOGIN() :
  db=open("databa.txt","r")
  user_id=input("ENTER THE EMAIL ID:")
  pass_id=input("ENTER THE PASSWORD:")
  d=[]
  f=[]
  for i in db :
    a,b=i.split(" ")
    b=b.strip()
    d.append(a)
    f.append(b)
  data = dict(zip(d, f))
  if user_id in d:
    if pass_id == data[user_id] :
      print("Login Success")
    else:
      print("password is wrong")
  else:
    print("[Email id is wrong] or [You are not registerd]")
def FORGOT_PASSWORD() :
  db=open("databa.txt","r")
  user_id=input("ENTER THE EMAIL ID:")
  d=[]
  f=[]
  for i in db:
    a,b=i.split(" ")
    d.append(a)
    f.append(b)
  data= dict(zip(d,f))
  if user_id in d:
    print("Your password is:",data[user_id])
  else :
    print("[User id is wrong] or [You are not Registered]")
db=open("databa.txt","a")
user_choice=input("would you like to [REGISTER|LOGIN|FORGOT_PASSWORD]:")
if user_choice=="REGISTER" :
  REGISTER()
elif user_choice=="LOGIN":
  LOGIN ()
elif user_choice=="FORGOT_PASSWORD" :
  FORGOT_PASSWORD()
else:
  print("please Enter correct input")

